runtime: python311

entrypoint: uvicorn app:app --host 0.0.0.0 --port $PORT

env_variables:
  MODEL_NAME: "gpt2"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
